[
    [r'id', r'input', r'expected', r'description'],
    [r'1', r'abcd', r'abcd', r'simple'],
    [r'2', r'abcd', r'abcd', r'quoted string in the midst of unquoted string'],
    [r'3', r'abcd', r'abcd', r'two quoted strings in the midst of unquoted string'],
    [r'4', r'ab\cd', r'ab{backslash}cd', r'escape is ignored when not in quotes'],
    [r'5', r'ab\\cd', r'ab{backslash}{backslash}cd', r'escape is ignored when not in quotes'],
    [r'6', r'ab\cd', r'ab{backslash}cd', r'escape is ignored when not in quotes'],
    [r'7', r'abcd', r'abcd', r'simple quoted string'],
    [r'8', r'ab"cd', r'ab{quote}cd', r'the quote is escaped'],
    [r'9', r'ab\cd', r'ab{backslash}cd', r'the backslash is escaped'],
    [r'10', r'ab\cd', r'ab{backslash}cd', r'escape is ignored because c is neither backslash nor quote'],
    [r'11', r'ab""cd', r'abcd', r'inquote, out of quote, back in quote'],
    [r'12', r'ab"-"cd', r'ab-cd', r'inquote, out of quote, back in quote'],
]
