[
    [r'input', r'expected', r'description'],
    [r'abcd', r'abcd', r'simple'],
    [r'abcd', r'abcd', r'quoted string in the midst of unquoted string'],
    [r'abcd', r'abcd', r'two quoted strings in the midst of unquoted string'],
    [r'ab\cd', r'ab{backslash}cd', r'escape is ignored when not in quotes'],
    [r'ab\\cd', r'ab{backslash}{backslash}cd', r'escape is ignored when not in quotes'],
    [r'ab\cd', r'ab{backslash}cd', r'escape is ignored when not in quotes'],
    [r'abcd', r'abcd', r'simple quoted string'],
    [r'ab"cd', r'ab{quote}cd', r'the quote is escaped'],
    [r'ab\cd', r'ab{backslash}cd', r'the backslash is escaped'],
    [r'ab\cd', r'ab{backslash}cd', r'escape is ignored because c is neither backslash nor quote'],
    [r'ab""cd', r'abcd', r'inquote, out of quote, back in quote'],
    [r'ab"-"cd', r'ab-cd', r'inquote, out of quote, back in quote'],
]
