[
    [r'**Excerpt from "Shadows in the Library" - Chapter 7**'],
    [None],
    [r'The dim library lights flickered as Detective Grayson pushed open the oak door. The young archivist, Emily Carter, stood frozen by the rare books cabinet, her hands trembling around a torn first edition.'],
    [None],
    [r'"Ms. Carter," Grayson said, stepping carefully around the overturned chair. "You called about a theft?"'],
    [None],
    [r'She spun around, eyes wide. "Not just a theft, Detective. Look." She pointed to the glass case. "They took only the 1793 Blake poetry volume but left behind more valuable books. And they did this..." Her finger traced strange symbols carved into the wood.'],
    [None],
    [r'Grayson crouched for a closer look. "These look recent. Any surveillance?"'],
    [None],
    [r'"System was down for maintenance," a deep voice interrupted. University Provost Henderson loomed in the doorway, his tailored suit at odds with the chaos. "I warned the board about skimping on security."'],
    [None],
    [r'Emily crossed her arms. "You also approved the maintenance schedule, Provost. Right after firing our night guard."'],
    [None],
    [r'''Henderson's face reddened. "Are you implying—"'''],
    [None],
    [r'''"I'm implying nothing," Emily shot back. "Just stating facts."'''],
    [None],
    [r'''Grayson stepped between them. "Let's focus. Ms. Carter, who knew about this particular book's location?"'''],
    [None],
    [r'"Just the rare books team. Dr. Langley, myself, and..." She hesitated.'],
    [None],
    [r'"And who?" Grayson pressed.'],
    [None],
    [r'''"Professor Wright. But he's been in Oxford all month."'''],
    [None],
    [r'''The provost scoffed. "Wright couldn't organize a tea party, let alone a theft."'''],
    [None],
    [r'''A new voice rasped from the shadows. "You'd be surprised what people can organize." Old Mr. Jenkins, the shelf-restorer, emerged from between stacks, polishing his glasses. "Saw a black van out back Tuesday night. Thought it was catering for the provost's dinner."'''],
    [None],
    [r'''Henderson stiffened. "That was Wednesday, you senile old—"'''],
    [None],
    [r'''"Enough." Grayson's voice cut through. "Jenkins, did you see anyone?"'''],
    [None],
    [r'"Just a tall figure in a long coat. Moved like a young man, but the way he carried himself... reminded me of someone."'],
    [None],
    [r'Emily gasped. "Not...?"'],
    [None],
    [r'Jenkins nodded grimly. "Like your grandfather, miss. Right before he disappeared."'],
    [None],
    [r'''The room fell silent. Grayson's notebook snapped shut. "I think I need to hear more about this grandfather."'''],
    [None],
    [r'---'],
    [None],
    [r'**Continued**'],
    [None],
    [r'''Emily's teacup clattered against its saucer. "Granddad vanished ten years ago after discovering something about Blake's works. He believed there was a coded—"'''],
    [None],
    [r'''"Ridiculous!" Henderson interrupted. "The man was dementia-ridden. Stole university property and—"'''],
    [None],
    [r'''"He did no such thing!" Emily stood so abruptly her chair toppled. "You've been covering this up for years!"'''],
    [None],
    [r'Grayson held up a hand. "Ms. Carter, what exactly did your grandfather discover?"'],
    [None],
    [r'Before she could answer, the lights went out. Glass shattered somewhere in the dark.'],
    [None],
    [r'"Everyone down!" Grayson shouted.'],
    [None],
    [r'A thud. A grunt. Then the emergency lights flickered on to reveal Jenkins clutching his arm, blood seeping between his fingers.'],
    [None],
    [r'"Man... at the fire exit," he panted.'],
    [None],
    [r'''Emily was already running. "The Blake facsimiles! They're all we have left!"'''],
    [None],
    [r'Grayson caught her wrist. "Too dangerous. Call an ambulance for Jenkins." He turned to Henderson, who was dialing his phone with shaking hands. "Provost, secure the building. No one leaves."'],
    [None],
    [r'''The provost's voice cracked. "You can't possibly think this is connected to—"'''],
    [None],
    [r'''"I think," Grayson said, shrugging off his jacket to press against Jenkins' wound, "that someone believes there's still something to find. And they're willing to kill for it." He met Emily's eyes. "Now. Tell me everything."'''],
    [None],
    [r'Outside, a car engine roared to life. Tires screeched. The chase had begun.'],
    [r'Echo mode ended.'],
]
