name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEBUG: "1"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify your Python version
    - name: make clean all
      run: make clean all
    - name: make test
      run: make test
    - name: make install
      run: make install prefix=./tmp
